ifneq (,$(wildcard ./.env))
include .env
export
ENV_FILE_PARAM = --env-file .env

endif

serv:
	python manage.py runserver

mmig:
	python manage.py makemigrations

mig:
	python manage.py migrate

shell:
	python manage.py shell

suser:
	python manage.py createsuperuser

cpass:
	python manage.py changepassword

cstatic:
	python manage.py collectstatic

