# Generated by Django 4.1.4 on 2023-01-06 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(None, 'Select LEVEL'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700')], max_length=100, null=True)),
                ('course', models.CharField(max_length=7, null=True)),
                ('question', models.TextField(default=None)),
                ('optionA', models.TextField(default=None)),
                ('optionB', models.TextField(default=None)),
                ('optionC', models.TextField(default=None)),
                ('optionD', models.TextField(default=None)),
                ('answer', models.CharField(max_length=1)),
                ('workings', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[(None, 'Select LEVEL'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700')], max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default=None)),
                ('optionA', models.TextField(default=None)),
                ('optionB', models.TextField(default=None)),
                ('optionC', models.TextField(default=None)),
                ('optionD', models.TextField(default=None)),
                ('answer', models.CharField(max_length=1)),
                ('workings', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=7, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.mylevel')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
