# Generated by Django 4.1.4 on 2022-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='database',
            name='course',
        ),
        migrations.AddField(
            model_name='database',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='school',
            field=models.CharField(choices=[('SEET', 'SEET'), ('SAAT', 'SAAT'), ('SET', 'SET'), ('SEMS', 'SEMS'), ('SPS', 'SPS'), ('SOC', 'SOC'), ('SOS', 'SOS')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='workings',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='question',
            field=models.CharField(max_length=10000),
        ),
    ]
