# Generated by Django 4.1.4 on 2022-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_remove_database_course_database_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='optionC',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='database',
            name='optionD',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='database',
            name='optionA',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='database',
            name='optionB',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
