# Generated by Django 4.1.4 on 2023-01-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='name',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mylevel',
            name='name',
            field=models.CharField(blank=True, choices=[(None, 'Select LEVEL'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700')], max_length=7, null=True, unique=True),
        ),
    ]
