# Generated by Django 4.1.4 on 2023-01-20 19:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_mycourse_name_alter_mylevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mylevel',
            name='name',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700')], default='100', max_length=7, null=True, unique=True),
        ),
    ]
